version: "3.9"
services:
  mochaserver:
    env_file:
        - ./server/.server.env
    build: 
        context: ./server
        dockerfile: ../dockerfile-local.dockerfile
    ports:
      - "8080:80"
      - "4433:443"
    volumes:
      - keys:/etc/letsencrypt/

volumes:
  keys: