version: "3.9"
services:
  dapp:
    env_file:
      - .dapp.env
    build: 
      context: .
      dockerfile: dockerfile
    
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - keys:/etc/letsencrypt/

volumes:
  keys: