version: "3.9"
services:
  mochaserver:
    env_file:
      - .server.env
    build: 
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - keys:/etc/letsencrypt/

volumes:
  keys: